language: python
python:
  - "3.5"
sudo: required

notifications:
  email:
    recipients:
      sbadillo@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

branches:
  only:
  - sources

env:
  global:
    secure: "EyP2HmpbzhD0dB/kLfgGUqz9+swvaNiFPGGez9KmCbywoR6WDZCpYae1Q3wP2jjZqWB+x04F05JL5iZnros9Z2/x2h24ztN/bkyFdK7Mrtofbx0aWGpXA1GwYNMNBuQIXuhvKUE0FmPYabn2hw1PYxMqw1BEJOsF1dbmLa9RmAF+tzSaLbBSO1aqpntnxVAYv6kMMoDfDGPVk9A76gilZjDgOCxhSMugmCMmiIyke7r6THlSU7Wk8ORqBcF/pfQKqOmSOlIN4uhQk5Dq2/BE/rkwv/MW0mE/7gSugx7uHCLjL0TVtGAQfLCpUBmQiNbHp1TOIaJo/rTLYlBy2MfFsu9eX7TNyOYpMNwcYB2yDKJ/o2laJ/PnLExqCBygIfZublLw73HifYVsN9zyUCIxv6jtXJQZdPl/fiyZuQC9hac8OQ98DMVKyMfhjTbSBaRIKyTtdAuuM1xSik3ndAe7bt1AKvDKVPUp6Aw+fJP1/jmL8nSjAGCx4fA4FPP0C1w4I0bfU+p5/81WwoSfdPOO9D386U08d/1QH2/2oyCeC2Sv39iaZuSEbN2Iz6h8nvogAFzSKIXoMp1Fqdkp2EjJODsMWk4yak5u0CeO+cZm2vGcLw6okYHOSMG5vREvYbMGTN+ITcQkJUy3aSxGtfiO6EywNWqMgue1ewZy0YY4qh4="

install:
- pip install -r requirements.txt
   
script:

- make publish github
